### ISSUE TITLE
Constant Guid expression generates invalid IL

### ISSUE THREAD

**Issue by detoxhby** [dadhi/FastExpressionCompiler#15] opened 2017-08-07 13:40 UTC
Any expression that contains ConstantExpression with Guid value will generate invalid IL:
```c#
$x.Id == .Constant<System.Guid>(cd0e7440-45dd-420a-a91d-67a99b67b26f)
```

The bigest problem is that the compilation does not fail and it won't fallback to normal `.Compile()`, but executing the produced delegate throws `System.InvalidProgramException`. (stacktrace's top element is the Closure) There is no way to reliably predict and handle this behaviour.

I couldn't debug into the produced func (as IL does not contain marked sequence points).

If you need the generated IL please tell me how to acquire it at runtime, thanks.

**Comment by dadhi** [comment] 2017-08-07 15:12
Thanks, will check.

**Comment by detoxhby** [comment] 2017-08-07 16:43
Made an example: https://dotnetfiddle.net/cj9iCu

**Comment by dadhi** [comment] 2017-08-07 20:09
Thanks for live repro-test. Will look together with #14, seems like in the same area.

**Comment by dadhi** [comment] 2017-08-08 06:41
Indeed the duplicate of #14. Fix is on the way.

**Closed** 2017-08-08 07:40 UTC
Labels: bug
